config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :plans, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      get 'mypage'
      get 'search'
    end
    member do
      get 'favorites'
    end
    resources :contents, only: [:new, :create, :edit, :update, :destroy] do
      collection do
        get 'map'
      end
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :plan
  belongs_to :user

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @plan = Plan.find(params[:plan_id])
    @favorite = current_user.favorites.new(plan_id: @plan.id)
    @favorite.save
  end

  def destroy
    @plan = Plan.find(params[:plan_id])
    @favorite = current_user.favorites.find_by(plan_id: @plan.id)
    @favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorites.html.erb
<% if plan.favorited_by?(current_user) %>
  <%= link_to plan_favorites_path(plan), method: :delete, remote: true do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;" id="liking-btn"></i>
  <%= plan.favorites.count %>
  <% end %>
<% else %>
  <%= link_to plan_favorites_path(plan), method: :post, remote: true do %>
    <i class="far fa-heart" aria-hidden="true" id="nolike-btn"></i>
  <%= plan.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @plan.id %>').html("<%= j(render "favorites/favorites", plan: @plan) %>");

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @plan.id %>').html("<%= j(render "favorites/favorites", plan: @plan) %>");