config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :plans, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      get 'mypage'
      get 'search'
    end
    member do
      get 'favorites'
    end
    resources :contents, only: [:new, :create, :edit, :update, :destroy] do
      collection do
        get 'map'
      end
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord

  has_many :contents, dependent: :destroy
  belongs_to :user
  belongs_to :comment, optional:true
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :travel, presence: true

  has_one_attached :image

  enum travel: {
    hokkaido: 0, aomori: 1, iwate: 2, miyagi: 3, akita: 4, yamagata: 5, fukushima: 6, ibaraki: 7, tochigi: 8, gunma: 9, saitama: 10, chiba: 11, tokyo: 12, kanagawa: 13,
    niigata: 14, toyama: 15, ishikawa: 16, fukui: 17, yamanashi: 18, nagano: 19, gifu: 20, shizuoka: 21, aichi: 22, mie: 23, shiga: 24, kyoto: 25, osaka: 26, hyogo: 27,
    nara: 28, wakayama: 29, tottori: 30, shimane: 31, okayama: 32, hiroshima: 33, yamaguchi: 34, tokushima: 35, kagawa: 36, ehime: 37, kochi: 38, fukuoka: 39, saga: 40,
    nagasaki: 41, kumamoto: 42, oita: 43, miyazaki: 44, kagoshima: 45, okinawa: 46
  }

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io:File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search != ""
      search = search.delete("都") #引数の("都")を削除
      search = search.delete("県")
      search = search.delete("府")
      Plan.where(['title LIKE(?) OR travel LIKE(?)', "%#{search}%", self.prefecture_num(search)])
    else
      Plan.includes(:user).order('created_at DESC')
    end
  end

  def self.prefecture_num(prefecture_kanji)
    self.kanji_prefecture_hash[prefecture_kanji]
  end

  def self.kanji_prefecture_hash
    {"北海道"=> 0, "青森"=> 1, "岩手"=> 2, "宮城"=> 3, "秋田"=> 4, "山形"=> 5, "福島"=> 6, "茨城"=> 7, "栃木"=> 8, "群馬"=> 9, "埼玉"=> 10, "千葉"=> 11, "東京"=> 12,
     "神奈川"=> 13, "新潟"=> 14, "富山"=> 15, "石川"=> 16, "福井"=> 17, "山梨"=> 18, "長野"=> 19, "岐阜"=> 20, "静岡"=> 21, "愛知"=> 22, "三重"=> 23, "滋賀"=> 24,
     "京都"=> 25, "大阪"=> 26, "兵庫"=> 27, "奈良"=> 28, "和歌山"=> 29, "鳥取"=> 30, "島根"=> 31, "岡山"=> 32, "広島"=> 33, "山口"=> 34, "徳島"=> 35, "香川"=> 36,
     "愛媛"=> 37, "高知"=> 38, "福岡"=> 39, "佐賀"=> 40, "長崎"=> 41, "熊本"=> 42, "大分"=> 43, "宮崎"=> 44, "鹿児島"=> 45, "沖縄"=>46}
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  before_action :correct_user, only: [:edit, :update, :destroy]

  before_action :move_to_index, except: [:index]

  before_action :set_user, only: [:favorites]

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    @plan.travel = Plan.travels[plan_params[:travel]]
    if @plan.save
      redirect_to new_plan_content_path(@plan.id)
    else
      render :new
    end
  end

  def index
    @plans = Plan.page(params[:page])
  end

  def show
    @plan = Plan.find(params[:id])
    @contents = Content.where(plan_id: @plan.id)
    @comments = Comment.where(plan_id: @plan.id)
    @comment = Comment.new
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params)
      redirect_to plan_path(@plan.id)
    else
      render :edit
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path
  end

  def mypage
    @plans = Plan.where(user_id: current_user.id).page(params[:page])
    @user = current_user
  end

  def favorites
    @favorites = Favorite.where(user_id: @user.id).pluck(:plan_id)
    @favorite_plans = Kaminari.paginate_array(Plan.find(@favorites)).page(params[:page])
    @user = current_user
  end

  def search
    @plans = Plan.search(params[:keyword]).page(params[:page])
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :image, :travel)
  end

  def correct_user
    @plan = Plan.find(params[:id])
    unless @plan.user == current_user
      redirect_to plans_path
    end
  end

  def move_to_index
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_plan_error.html.erb
  <% if resource.errors.any? %>
    <% if errors_hash(resource)[col].present? %>
      <% errors_hash(resource)[col].each do |error_msg| %>
        <p><%= error_msg %></p>
      <% end %>
    <% end %>
  <% end %>

app/views/plans/edit.html.erb
<div class="newplan-box">
  <div class="newplan-box-inner">
    <h1>旅行プラン編集</h1>

    <%= form_with model:@plan, local:true do |f| %>

      <div class="newplan-box-title">
        <%= f.label :title, "タイトル" %><span>必須</span><br>
        <%= f.text_field :title, placeholder: "例)沖縄旅行1日目" %>
        <%= render "plans/plan_error", col: :title, resource: @plan %>
      </div>

      <div class="newplan-box-travel">
        <%= f.label :travel, "旅行先(都道府県)" %><span>必須</span><br>
        <%= f.select :travel, options_for_select(Plan.travels_i18n.invert, :selected => @plan.travel) %>
        <%= render "plans/plan_error", col: :travel, resource: @plan %>
      </div>

      <div class="newplan-box-image-text">メイン画像</div>
      <div class="newplan-box-image">
        <%= f.label :image, "画像を選択" %>
        <%= f.file_field :image, accept: "image/*" %>
      </div>

      <div id="new-image"></div>

      <div class="newplan-box-submit">
        <%= f.submit "編集" %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'preview' %>

app/views/plans/favorites.html.erb
  <div class="mypage">
    <div class="mypage-top">
    <%= link_to edit_user_registration_path, class: 'text-dark' do %>
      <% if @user.image.attached? %>
        <%= image_tag @user.get_image(2000,2000), class: 'icon' %>
      <% else %>
        <%= image_tag 'no_image.jpg', class: 'icon' %>
      <% end %>
      <%= @user.name %>さん
    <% end %>
    </div>
    <div class="mypage-box">
      <% @favorite_plans.each do |plan| %>
        <%= link_to plan_path(plan.id) do %>
        <div class="mypage-box-body">
          <div class="mypage-box-body-upr">
            <%= image_tag plan.get_image(2000,2000), class: 'mypage-box-image' %>
          </div>
          <div class="mypage-box-body-lwr">
          <h3 class="mypage-box-travel"><%= plan.travel_i18n %></h3>
          <h3 class="mypage-box-title"><%= plan.title.truncate(14) %></h3>
        <% end %>
          <div class="mypage-favorite">
            <div class="mypage-create"><%= plan.created_at.strftime('%Y/%m/%d') %></div>
              <div id="favorite_buttons_<%= plan.id %>" class="favorite-button">
                <%= render "favorites/favorites", plan: plan %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
<%= paginate @favorite_plans, theme: 'twitter-bootstrap-4' %>

app/views/plans/index.html.erb
<div class="plan">
  <div class="plan-top"><i class="fas fa-plane"></i> みんなの旅行プラン</div>
  <div class="plan-box">
    <% @plans.each do |plan| %>
      <%= link_to plan_path(plan.id) do %>
        <div class="plan-box-body">
          <div class="plan-box-body-upr">
            <%= image_tag plan.get_image(2000,2000), class: 'plan-box-image' %>
          </div>
          <div class="plan-box-body-lwr">
            <h3 class="plan-box-travel"><%= plan.travel_i18n %></h3>
            <h3 class="plan-box-title"><%= plan.title.truncate(14) %></h3>
      <% end %>
            <div class="plan-favorite">
              <div class="plan-create"><%= plan.created_at.strftime('%Y/%m/%d') %></div>
              <div id="favorite_buttons_<%= plan.id %>" class="favorite-button">
                <%= render "favorites/favorites", plan: plan %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<%= paginate @plans, theme: 'twitter-bootstrap-4' %>

app/views/plans/mypage.html.erb
  <div class="mypage">
    <div class="mypage-top">
    <%= link_to edit_user_registration_path, class: 'text-dark' do %>
      <% if @user.image.attached? %>
        <%= image_tag @user.get_image(2000,2000), class: 'icon' %>
      <% else %>
        <%= image_tag 'no_image.jpg', class: 'icon' %>
      <% end %>
      <%= @user.name %>さん
    <% end %>
    </div>
    <div class="mypage-box">
      <% @plans.each do |plan| %>
        <%= link_to plan_path(plan.id) do %>
        <div class="mypage-box-body">
          <div class="mypage-box-body-upr">
            <%= image_tag plan.get_image(2000,2000), class: 'mypage-box-image' %>
          </div>
          <div class="mypage-box-body-lwr">
          <h3 class="mypage-box-travel"><%= plan.travel_i18n %></h3>
          <h3 class="mypage-box-title"><%= plan.title.truncate(14) %></h3>
        <% end %>
          <div class="mypage-favorite">
            <div class="mypage-create"><%= plan.created_at.strftime('%Y/%m/%d') %></div>
              <div id="favorite_buttons_<%= plan.id %>" class="favorite-button">
                <%= render "favorites/favorites", plan: plan %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
<%= paginate @plans, theme: 'twitter-bootstrap-4' %>

app/views/plans/new.html.erb
<div class="newplan-box">
  <div class="newplan-box-inner">
    <h1>旅行プラン作成</h1>

    <%= form_with model:@plan, local:true do |f| %>

      <div class="newplan-box-title">
        <%= f.label :title, "タイトル" %><span>必須</span><br>
        <%= f.text_field :title, placeholder: "例)沖縄旅行1日目" %>
        <%= render "plans/plan_error", col: :title, resource: @plan %>
      </div>

      <div class="newplan-box-travel">
        <%= f.label :travel, "旅行先(都道府県)" %><span>必須</span><br>
        <%= f.select :travel, options_for_select(Plan.travels_i18n.invert), {prompt: "都道府県を選択してください"} %>
        <%= render "plans/plan_error", col: :travel, resource: @plan %>
      </div>

      <div class="newplan-box-image-text">メイン画像</div>
      <div class="newplan-box-image">
        <%= f.label :image, "画像を選択" %>
        <%= f.file_field :image, accept: "image/*" %>
      </div>

      <div id="new-image"></div>

      <div class="newplan-box-submit">
        <%= f.submit "旅行プラン詳細入力へ進む" %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_pack_tag 'preview' %>

app/views/plans/search.html.erb
<div class="plan">
  <div class="plan-top"><i class="fas fa-plane"></i> みんなの投稿</div>
  <% if @plans == [] %>
    <h2 class="seach-result">検索結果はありません</h2>
  <% else %>
    <div class="plan-box">
      <% @plans.each do |plan| %>
        <%= link_to plan_path(plan.id) do %>
          <div class="plan-box-body">
            <div class="plan-box-body-upr">
              <%= image_tag plan.get_image(2000,2000), class: 'plan-box-image' %>
            </div>
            <div class="plan-box-body-lwr">
              <h3 class="plan-box-travel"><%= plan.travel_i18n %></h3>
              <h3 class="plan-box-title"><%= plan.title.truncate(14) %></h3>
        <% end %>
              <div class="plan-favorite">
                <div class="plan-create"><%= plan.created_at.strftime('%Y/%m/%d') %></div>
                <div id="favorite_buttons_<%= plan.id %>" class="favorite-button">
                  <%= render "favorites/favorites", plan: plan %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  <% end %>
</div>
<%= paginate @plans, theme: 'twitter-bootstrap-4' %>

app/views/plans/show.html.erb
<div class="show-box">

  <h1><%= @plan.title %></h1>

  <div class="content">
    <ul class="content-list">
      <% @contents.each do |content| %>
      <li>
        <div class="content-heading">
          <div class="content-order">
            <p><%= content.order %></p>
          </div>
          <div class="content-hour"><%= content.hour %>:<%= content.minute %></div>
          <div class="content-place"><%= content.place %></div>
        </div>
        <div class="content-line">
          <div class="content-image"><%= image_tag content.get_image(2000,2000), class: 'show-box-image' %></div>
          <div class="content-explanation"><%= safe_join(content.explanation.split("\n"),tag(:br)) %></div>
          <div class="content-info">【観光地・店舗】の基本情報</div>
          <div class="content-info-box">
            <div class="content-info-text">名称</div>
            <div class="content-info-data"><%= content.name %></div>
          </div>
          <div class="content-info-box">
            <div class="content-info-text">住所</div>
            <%= link_to map_plan_contents_path(@plan.id, order: content.order) do %> 
              <div class="content-info-data"><%= content.address %></div>
            <% end %>
          </div>
          <div class="content-info-box">
            <div class="content-info-text">電話番号</div>
            <div class="content-info-data"><%= content.telephonenumber %></div>
          </div>
          <div class="content-info-box">
            <div class="content-info-text">アクセス</div>
            <div class="content-info-data"><%= content.access %></div>
          </div>
         <div class="content-info-box">
           <div class="content-info-text">営業時間</div>
            <div class="content-info-data"><%= content.businesshours %></div>
          </div>
          <div class="content-info-box">
            <div class="content-info-text">予約</div>
            <div class="content-info-data"><%= content.reservation %></div>
          </div>
          <div class="content-info-box">
            <div class="content-info-text">料金</div>
            <div class="content-info-data"><%= content.price %></div>
          </div>
          <div class="content-info-box">
            <div class="content-info-text">滞在時間</div>
            <div class="content-info-data"><%= content.stay_time %></div>
          </div>
          <div class="content-info-box">
            <div class="content-info-text">評価</div>
            <div class="content-info-data" id="star-rate-<%= content.id %>"></div>
                <script>
                  $('#star-rate-<%= content.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= content.rate %>,
                  });
                </script>
          </div>
        </div>

        <div></div>

        <div class="content-change1">
          <% if @plan.user == current_user %>
            <%= link_to "編集", edit_plan_content_path(@plan.id, content.id), class: 'btn btn-sm btn-success' %>
            <%= link_to "削除", plan_content_path(@plan.id, content.id), class: 'btn btn-sm btn-danger', method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <% end %>
        </div>
      </li>
      <% end %>

    </ul>

    <div class="content-change2">
    <% if @plan.user == current_user %>
      <%= link_to "行先を追加", new_plan_content_path(@plan.id), class: 'btn btn-sm btn-primary' %>
      <%= link_to "タイトルを編集", edit_plan_path(@plan.id), class: 'btn btn-sm btn-success' %>
      <%= link_to "プランを削除", plan_path(@plan.id), class: 'btn btn-sm btn-danger', method: :delete, "data-confirm" => "本当に削除しますか？" %>
    <% end %>
    </div>

    <div class="comment">
      <div class="comment-text"><i class="far fa-comment"></i> みんなのコメント</div>
        <div class="comment-body">
          <div class="comment-name">
            <% if current_user.image.attached? %>
              <%= image_tag current_user.get_image(2000,2000), class: 'icon' %>
            <% else %>
              <%= image_tag 'no_image.jpg', class: 'icon' %>
            <% end %>
            <%= current_user.name %>さん
          </div>
          <div class="comment-area">
            <%= form_with model: [@plan,@comment], local: true do |f| %>
              <%= f.text_area :comment, placeholder: "コメントを入れてください" %>
              <%= f.submit "投稿する" %>
            <% end %>
          </div>
        </div>

      <ul class="comment-list">
        <% @comments.each do |c| %>
        <li>
          <div class="all-comment-name">
            <% if c.user.image.attached? %>
              <%= image_tag c.user.get_image(2000,2000), class: 'icon' %>
            <% else %>
              <%= image_tag 'no_image.jpg', class: 'icon' %>
            <% end %>
            <%= c.user.name %>さん
          </div>
          <div class="all-comment-area">
            <%= safe_join(c.comment.split("\n"),tag(:br)) %>
            <div class="comment-destroy">
              <% if c.user == current_user %>
                <%= link_to "コメント削除", plan_comment_path(@plan.id, c.id), class: 'btn btn-sm btn-danger', method: :delete, "data-confirm" => "本当に削除しますか？" %>
              <% end %>
            </div>
          </div>
        </li>
        <% end %>
      </ul>
      <div class="more">
        <button>コメントをもっと見る</button>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'more' %>