config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :plans, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      get 'mypage'
      get 'search'
    end
    member do
      get 'favorites'
    end
    resources :contents, only: [:new, :create, :edit, :update, :destroy] do
      collection do
        get 'map'
      end
    end
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelRecommendPlan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
      <header class="shadow-sm">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <a class="navbar-brand p-3" href="/"><%= image_tag 'ryokou.png', size: '50x50', :alt => '旅行アイコン' %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <% if user_signed_in? %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to new_plan_path, class: 'nav-link text-dark' do %>
                  <i class="far fa-edit"></i>投稿
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to mypage_plans_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-user-tag"></i>マイページ
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to favorites_plan_path(current_user), class: 'nav-link text-dark' do %>
                  <i class="far fa-heart"></i>いいね
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to plans_path, class: 'nav-link text-dark' do %>
                  <i class="far fa-list-alt"></i>一覧
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
                  <i class="fas fa-sign-out-alt"></i>ログアウト
                <% end %>
              </li>
              <li class="nav-item mx-2">
                <%= form_with url: search_plans_path, method: :get, local: true do |f| %>
                  <%= f.text_field :keyword, placeholder: "投稿を検索する" %>
                  <%= f.submit "検索", class: 'search-btn' %>
                <% end %>
              </li>
            </ul>
            <% else %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item mx-4">
                <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                  <i class="fas fa-user-plus"></i> 新規登録
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
      </header>

    <main class="mb-auto">
      <%= yield %>
    </main>

    <footer class="text-center bg-dark text-white pt-4 pb-4">
      Copyright © Infratop Inc. All Rights Reserved.
    </footer>
  </body>
</html>